services:
    PhilTenno\FilesSyncGo\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Tests,Kernel.php}'
        autowire: true
        autoconfigure: true

    # Controller explizit
    PhilTenno\FilesSyncGo\Controller\FilesSyncGoController:
        autowire: true
        autoconfigure: true
        public: true
        tags: ['controller.service_arguments']

    # Service explizit
    PhilTenno\FilesSyncGo\Service\FilesSyncGoService:
        autowire: true
        arguments: ['@logger']
        public: true

    # Settings explizit
    PhilTenno\FilesSyncGo\Service\FilesSyncSettings:
        autowire: true